### PR TITLE
Update general-changelog-dv.md

### PR DESCRIPTION
**Pull request by mddifilippo89**
mdd-update-21.2-changelog

### CODE REVIEW

**Comment by mddifilippo89** [comment]
@zdrawku 
@HUSSAR-mtrela 

Angular docs are failing due what appears to be a merge issue
http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/_build/index?buildId=822895&_a=summary

**Comment by zdrawku** [comment]
@mddifilippo89 usually this type of problems appear when there are changes in common topics hence the merge conflicts.

As I recall @HUSSAR-mtrela and @gedinakova agreed on exclusing the overlapping topics from the AngularDocfx_EN output (mail thread name "WC vs Angular LOB controls").

I manually checked whether this is the case and indeed the build error is caused by merge conflict with the calendar.md topic:

image

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
this PR is on hold until other changes are merged from xplat-docs

**Comment by mddifilippo89** [comment]
@zdrawku @HUSSAR-mtrela 

Can we prevent "changelog" in the url to github to not be case sensitive without adding a redirect? Github wants it to be all capital letters. I've noticed markdown will autocorrect this and lowercase them.
https://github.com/igniteui/igniteui-angular/blob/master/changelog.md

see hyperlink here:
https://staging.infragistics.com/angularsite/components/general-changelog-dv

**Comment by HUSSAR-mtrela** [comment]
closing obsolete PR

**Pull request closed without merging**
