### PR TITLE
Translated rewritten slider topic

### PR DESCRIPTION
**Pull request by ig-ealbert**
Translated the raw file as provided in the slider-docs-rework branch.

One thing I noticed is that the language metadata is removed.  Is that intentional?  It's removed in the rewritten English topic and I simply copied what was there.

### CODE REVIEW

**Comment by kdinev** [comment]
@simeonoff Can you answer Liz' question?

**Comment by ig-ealbert** [comment]
Now that #74 has been merged, what do I do with this pull request?

**Comment by kdinev** [comment]
@ig-ealbert I can merge it. It won't make a difference.

**Comment by ig-ealbert** [comment]
Redid this in #97.

**Pull request closed without merging**
