### PR TITLE
#47 igxCard topic enhancement.

### PR DESCRIPTION
**Pull request by gedinakova**
#47 Enriched igxCard article with a step-by-step tutorial for creating a card.

### CODE REVIEW

**Comment by ig-ealbert** [comment]
I have retranslated the content that is in the pull request and will wait for review before updating the file here.  Same would apply if more content is added as suggested.

**Comment by ig-ealbert** [comment]
@gedinakova @simeonoff @kdinev I am unable to find Galina's repository so I can make a pull request to it.  Note how there are no repositories here: https://github.com/gedinakova
What I have done is to add her GitHub as a remote, but there is no igniteui-docfx project there, so I cannot fetch it or create a pull request to her repository.  How should I proceed?  Should I email the completed file to someone?

**Comment by ig-ealbert** [comment]
Another option is to complete this pull request and I will make a separate one to add the Japanese topic.  Let me know which is preferable.

**Comment by alhalama** [comment]
@ig-ealbert Galina's changes are in a branch on IgniteUI's igniteui-docfx repo: https://github.com/IgniteUI/igniteui-docfx/tree/gedinakova/igxCardArticleUpdate

**Comment by ig-ealbert** [comment]
I have created a pull request onto Galina's branch.

**Pull request merged**
