### PR TITLE
Changes from AngularDocFX_KR

### PR DESCRIPTION
**Pull request by ESShared**

### CODE REVIEW

**Comment by HristoP96** [comment]
Most of the files are with wrong name and after the build they cannot be reached. 
@HUSSAR-mtrela  how can fix this.

**Comment by HUSSAR-mtrela** [comment]
@HristoP96 this PR should build with this PR #1735

**Comment by zdrawku** [comment]
Thank you Martin for making the manual changes, I've added a minor update to the TOC as well because the CategoryChart section was missing./

**Comment by zdrawku** [comment]
Keep in mind that some of the files are not present, although they are now referenced with the TOC:
https://github.com/IgniteUI/igniteui-docfx/pull/1735/commits/179e7a8d3b3b5ea48f19b91e30b8fe837780ed06#diff-1c87544cc4ba80f21537961dc80cc67fR369
https://github.com/IgniteUI/igniteui-docfx/pull/1735/commits/179e7a8d3b3b5ea48f19b91e30b8fe837780ed06#diff-1c87544cc4ba80f21537961dc80cc67fR402
https://github.com/IgniteUI/igniteui-docfx/pull/1735/commits/179e7a8d3b3b5ea48f19b91e30b8fe837780ed06#diff-1c87544cc4ba80f21537961dc80cc67fR477

**Pull request merged**
